[mail function]
; For Win32 only.
; http://php.net/smtp
SMTP=smtp.gmail.com
smtp_port=587
; For Win32 only.
sendmail_from = kaderbelem428@gmail.com

; Authentification pour Gmail
auth_username = kaderbelem428@gmail.com
auth_password = xvwhrrpygjmdlhnw
